export type ComunaPrograma = {
  comuna: string;
  nombre_programa: string;
  descripcion: string;
  direccion?: string | null;
  telefono?: string | null;
  correo?: string | null;
  link?: string | null;
  tipo_link?: "DEDICADA" | "TAG" | "DIDECO" | "PORTADA";
  nota?: string | null;
};

// Datos en código — misma fuente que la tabla Supabase comunas_adulto_mayor.
// Para agregar una nueva comuna: INSERT en Supabase Y agregar aquí.
// Última actualización: 30-07-2026 — expandido a 35 comunas Gran Santiago.
// URLs verificadas por agente web + HTTP check. Ver tabla de confianza en CLAUDE.md.
export const COMUNAS_DATA: ComunaPrograma[] = [
  // ── Gran Santiago — ordenadas alfabéticamente ──────────────────────────
  {
    comuna: "Cerrillos",
    nombre_programa: "DIDECO Cerrillos — Adulto Mayor",
    descripcion: "Programas sociales y talleres para personas mayores a través de la Dirección de Desarrollo Comunitario.",
    direccion: "Las Hortensias 400, Cerrillos",
    telefono: "2 870 7887",
    correo: "sec_dideco@mcerrillos.cl",
    link: "https://www.mcerrillos.cl",
    tipo_link: "PORTADA",
    nota: "Sin página web dedicada. Contactar directamente a DIDECO.",
  },
  {
    comuna: "Cerro Navia",
    nombre_programa: "Oficina de Personas Mayores Cerro Navia",
    descripcion: "Atención directa, talleres y programas de integración social para personas mayores.",
    direccion: "Del Consistorial 6645, Cerro Navia",
    telefono: "22 380 4217",
    link: "https://www.cerronavia.cl/oficina-personas-mayores/",
    tipo_link: "DEDICADA",
    nota: "Lunes a viernes 8:30–14:00.",
  },
  {
    comuna: "Conchalí",
    nombre_programa: "Área Adulto Mayor DIDECO Conchalí",
    descripcion: "Equipo técnico especializado con programas de integración, talleres y actividades sociales.",
    direccion: "Los Minerales 3478, Conchalí",
    telefono: "+56 228 286 100",
    link: "https://conchali.cl/adulto-mayor/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "El Bosque",
    nombre_programa: "Centro Gerontológico El Bosque",
    descripcion: "Atención gerontológica integral, talleres y actividades recreativas para personas mayores.",
    direccion: "Baquedano 11.015, El Bosque",
    telefono: "228293317",
    correo: "bosquemayor@municipalidadelbosque.cl",
    link: "https://www.municipalidadelbosque.cl/tramites-y-beneficios/adultos-mayores-centro-gerontologico/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Estación Central",
    nombre_programa: "Oficina de Personas Mayores Estación Central",
    descripcion: "Atención, orientación y programas para personas mayores de la comuna.",
    direccion: "Nocedal 320, Estación Central",
    telefono: "(+569) 2793 2256",
    link: "https://muniecentral.cl",
    tipo_link: "PORTADA",
    nota: "Sin página web dedicada. Sitio municipal presenta inestabilidad. Contactar por teléfono.",
  },
  {
    comuna: "Huechuraba",
    nombre_programa: "Oficina Comunal para Personas Mayores Huechuraba",
    descripcion: "Programas biopsicosociales, talleres y actividades de integración para personas mayores.",
    direccion: "Pablo Neruda 5901, Huechuraba",
    correo: "personasmayores@huechuraba.cl",
    link: "https://www.huechuraba.cl/dideco/area-integracion-social/oficina-comunal-para-personas-mayores",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Independencia",
    nombre_programa: "Oficina del Adulto Mayor Independencia",
    descripcion: "Tres programas: Oficina Personas Mayores, Cuidados Domiciliarios y CEDIAM (dos sedes).",
    direccion: "Gamero 541, Independencia",
    link: "https://www.independencia.cl/oficinas-municipales/adulto-mayor/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "La Cisterna",
    nombre_programa: "Casa del Adulto Mayor La Cisterna",
    descripcion: "Centro comunitario con talleres, actividades recreativas y programas de integración social.",
    link: "http://www.cisterna.cl/011-casa-del-adulto-mayor.php",
    tipo_link: "DEDICADA",
    nota: "El sitio puede devolver error HTTP desde redes externas; contenido verificado vía buscador.",
  },
  {
    comuna: "La Florida",
    nombre_programa: "Programa Adulto Mayor La Florida",
    descripcion: "Gestión territorial, protección de derechos, programa Vínculos y talleres para personas mayores.",
    link: "https://www.laflorida.cl/sitio/programas/programa-adulto-mayor/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "La Granja",
    nombre_programa: "Programa Adulto Mayor La Granja",
    descripcion: "Talleres y actividades municipales para personas mayores.",
    telefono: "225503700",
    link: "https://www.municipalidadlagranja.cl/tag/adulto-mayor/",
    tipo_link: "TAG",
    nota: "Sin página dedicada; la URL directa /oficina-del-adulto-mayor/ no está disponible.",
  },
  {
    comuna: "La Pintana",
    nombre_programa: "DIPEMA La Pintana",
    descripcion: "Dirección de Personas Mayores con cobertura a más de 25.000 residentes mayores de la comuna.",
    direccion: "Porto Alegre 12.537, La Pintana",
    link: "https://pintana.cl/?page_id=3415",
    tipo_link: "DEDICADA",
    nota: "URL dinámica (WordPress); puede cambiar si el sitio migra.",
  },
  {
    comuna: "La Reina",
    nombre_programa: "Oficina de Protección al Adulto Mayor La Reina",
    descripcion: "Atención personalizada, talleres y orientación para personas mayores de la comuna.",
    direccion: "Av. F. Castillo Velasco 8602, La Reina",
    telefono: "225927394",
    correo: "nperalta@mlareina.cl",
    link: "https://www.lareina.cl/oficina-de-proteccion-al-adulto-mayor/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Las Condes",
    nombre_programa: "Dirección de Desarrollo Comunitario — Adulto Mayor",
    descripcion: "Múltiples programas: círculos de encuentro, centros de día, talleres de arte y estimulación cognitiva.",
    link: "https://www.lascondes.cl/soy-vecino/adulto-mayor/",
    tipo_link: "DEDICADA",
    nota: "Inscripción presencial en DIDECO Las Condes.",
  },
  {
    comuna: "Lo Barnechea",
    nombre_programa: "Círculo Senior y Centro de Día Lo Barnechea",
    descripcion: "Círculo Senior activo y Centro de Día para personas mayores de la comuna.",
    direccion: "Av. Raúl Labbé 13.989, Lo Barnechea",
    telefono: "22 757 3592",
    link: "https://lobarnechea.cl/comunidades/adulto-mayor/",
    tipo_link: "DEDICADA",
    nota: "El sitio puede devolver error HTTP desde redes externas; contenido verificado vía buscador.",
  },
  {
    comuna: "Lo Espejo",
    nombre_programa: "Oficina de Personas Mayores Lo Espejo",
    descripcion: "Programas de integración social y talleres para personas mayores de la comuna.",
    direccion: "Av. Central C.R. Silva Henríquez 8321, Lo Espejo",
    telefono: "22 485 6085",
    link: "https://www.loespejo.cl",
    tipo_link: "PORTADA",
    nota: "Sin página web dedicada. Contactar directamente a la oficina.",
  },
  {
    comuna: "Lo Prado",
    nombre_programa: "Adulto Mayor DIDECO Lo Prado",
    descripcion: "Siete áreas de servicio: salud, recreación, cultura, deporte, talleres formativos y más.",
    direccion: "San Pablo 5959, Lo Prado",
    telefono: "—",
    correo: "claudia.rosales@loprado.cl",
    link: "https://loprado.cl/dideco/proteccion-social/adulto-mayor/",
    tipo_link: "DEDICADA",
    nota: "Lunes a viernes 9:00–14:00.",
  },
  {
    comuna: "Macul",
    nombre_programa: "Centro Integral del Adulto Mayor (CIAM) Macul",
    descripcion: "Centro integral con gimnasio y auditorium para personas mayores de la comuna.",
    direccion: "Av. Quilín 3675, Macul",
    telefono: "228739269",
    link: "https://www.munimacul.cl/portalnv/index.php/centro-integral-del-adulto-mayor-ciam/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Maipú",
    nombre_programa: "Oficina del Adulto Mayor Maipú",
    descripcion: "Programas municipales para personas mayores: talleres, actividades y orientación.",
    telefono: "22 402 8201",
    correo: "oficinadeladultomayor@maipu.cl",
    link: "https://municipalidadmaipu.cl/tag/oficina-del-adulto-mayor/",
    tipo_link: "TAG",
    nota: "Sin página dedicada; categoría de noticias activa. Tel. alternativo: 22 402 8203.",
  },
  {
    comuna: "Ñuñoa",
    nombre_programa: "Departamento de la Persona Mayor Ñuñoa",
    descripcion: "Talleres culturales, recreativos y sociales en modalidad presencial y virtual.",
    direccion: "Av. Grecia 4363 y Av. Irarrázaval 3550, Ñuñoa",
    link: "https://www.nunoa.cl/direcciones-y-coorporaciones/direccion-de-desarrollo-comunitario/departamento-de-la-persona-mayor/",
    tipo_link: "DEDICADA",
    nota: "Lunes a viernes 9:00–13:30.",
  },
  {
    comuna: "Padre Hurtado",
    nombre_programa: "Adulto Mayor Municipalidad de Padre Hurtado",
    descripcion: "Programas y actividades municipales para personas mayores de la comuna.",
    telefono: "2430 6000",
    correo: "contacto@mph.cl",
    link: "https://portal.mph.cl/?cat=2",
    tipo_link: "TAG",
    nota: "Categoría de noticias activa 2021–2026.",
  },
  {
    comuna: "Pedro Aguirre Cerda",
    nombre_programa: "DIDECO Pedro Aguirre Cerda — Adulto Mayor",
    descripcion: "Programas sociales para personas mayores a través de la Dirección de Desarrollo Comunitario.",
    direccion: "Uno Oriente 3939, Pedro Aguirre Cerda",
    link: "https://www.pedroaguirrecerda.cl/dideco-2/",
    tipo_link: "DIDECO",
    nota: "Sin página específica de adulto mayor. Consultar en DIDECO.",
  },
  {
    comuna: "Peñalolén",
    nombre_programa: "Unidad de Personas Mayores Peñalolén",
    descripcion: "135 clubes activos, talleres, turismo social y programas asociados a SENAMA.",
    link: "https://www.penalolen.cl/comuna-amigable-2/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Providencia",
    nombre_programa: "Departamento Personas Mayores Providencia",
    descripcion: "Talleres de actividad física, arte, cultura, finanzas, tecnología y trekking.",
    correo: "adultomayor@providencia.cl",
    link: "https://providencia.cl/provi/comunidad/personas-mayores/personas-mayores-departamento",
    tipo_link: "DEDICADA",
    nota: "WhatsApp: +56939142254. Requiere Tarjeta Vecino de Providencia para inscribirse.",
  },
  {
    comuna: "Pudahuel",
    nombre_programa: "Personas Mayores Pudahuel — Casa de Todas y Todos",
    descripcion: "Programas de integración y actividades sociales para personas mayores de la comuna.",
    direccion: "Av. La Estrella 962, Pudahuel",
    telefono: "22 445 5905",
    link: "https://www.mpudahuel.cl",
    tipo_link: "PORTADA",
    nota: "Sin página web dedicada. Contactar por teléfono a Casa de Todas y Todos.",
  },
  {
    comuna: "Puente Alto",
    nombre_programa: "Oficina del Adulto Mayor Puente Alto",
    descripcion: "Programas Vínculos, Viviendas Tuteladas, Centro Diurno y Cuidados Domiciliarios.",
    direccion: "Eduardo Cordero 0101, Puente Alto",
    telefono: "22 731 5335",
    link: "https://mpuentealto.cl/oficina-del-adulto-mayor/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Quilicura",
    nombre_programa: "Departamento de Personas Mayores Quilicura",
    descripcion: "Servicios biopsicosociales, talleres y programas de integración para personas mayores.",
    link: "https://ww2.muniquilicura.cl/adultos-mayores-2/",
    tipo_link: "DEDICADA",
    nota: "El sitio puede devolver error HTTP desde redes externas; contenido verificado vía buscador.",
  },
  {
    comuna: "Quinta Normal",
    nombre_programa: "DIDECO Quinta Normal — Adulto Mayor",
    descripcion: "Programas de integración social y talleres para personas mayores de la comuna.",
    direccion: "Carrascal 4447, Quinta Normal",
    telefono: "22892 8700",
    link: "https://www.quintanormal.cl",
    tipo_link: "PORTADA",
    nota: "Sin página web dedicada. El sitio municipal presenta intermitencias. Contactar a DIDECO.",
  },
  {
    comuna: "Recoleta",
    nombre_programa: "Programa Adulto Mayor Recoleta",
    descripcion: "Programas municipales y actividades para personas mayores de la comuna.",
    direccion: "Av. Recoleta 2774 piso 2, Recoleta",
    telefono: "+562 2945 7506",
    correo: "cpena@recoleta.cl",
    link: "https://www.recoleta.cl/category/adulto-mayor/",
    tipo_link: "TAG",
    nota: "URL /programa-adulto-mayor/ devuelve 404; se usa categoría de noticias verificada.",
  },
  {
    comuna: "Renca",
    nombre_programa: "Departamento Adulto Mayor Renca",
    descripcion: "Departamento municipal completo con Centro Diurno y programas de integración.",
    direccion: "Av. Dorsal s/n, Renca (Centro Diurno)",
    telefono: "226856626",
    link: "https://renca.cl/unidades-municipales/direccion-de-desarrollo-comunitario/departamento-adulto-mayor/",
    tipo_link: "DEDICADA",
    nota: "El sitio puede devolver error HTTP desde redes externas; contenido verificado vía buscador.",
  },
  {
    comuna: "San Bernardo",
    nombre_programa: "Oficina del Adulto Mayor San Bernardo",
    descripcion: "Programas municipales de atención y actividades para personas mayores.",
    telefono: "22 9270 829",
    correo: "carlaarevalo@sanbernardo.cl",
    link: "https://www.sanbernardo.cl/oficina-del-adulto-mayor/",
    tipo_link: "DEDICADA",
    nota: "El sitio puede devolver error HTTP desde redes externas; contenido verificado vía buscador.",
  },
  {
    comuna: "San Joaquín",
    nombre_programa: "Personas Mayores San Joaquín",
    descripcion: "Tres sedes de atención, talleres y programas para personas mayores de la comuna.",
    direccion: "Santa Rosa 2606 / Carlos Valdovinos 333 / Catruman 279, San Joaquín",
    correo: "personasmayores@sanjoaquin.cl",
    link: "https://sanjoaquin.cl/personas-mayores/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "San Miguel",
    nombre_programa: "Talleres Adulto Mayor San Miguel",
    descripcion: "Talleres rotativos por clubes y agrupaciones: cocina, baile de salón, tejido y más.",
    telefono: "224011709",
    correo: "personasmayores@sanmiguel.cl",
    link: "https://web.sanmiguel.cl/category/adulto-mayor/",
    tipo_link: "TAG",
    nota: "Sin página dedicada; categoría de noticias activa.",
  },
  {
    comuna: "San Ramón",
    nombre_programa: "Adulto Mayor San Ramón — Centro Renacer",
    descripcion: "Centro Renacer inaugurado 2024 con 430 m² dedicados a personas mayores.",
    link: "https://municipalidadsanramon.cl/tag/adultos-mayores/",
    tipo_link: "TAG",
    nota: "Sin página propia; categoría de noticias activa.",
  },
  {
    comuna: "Santiago",
    nombre_programa: "Centro Adulto Mayor Santiago",
    descripcion: "Talleres culturales, recreativos y sociales. Sede principal en Matucana 272.",
    direccion: "Matucana 272, Parque Quinta Normal, Santiago",
    telefono: "7136500",
    link: "https://www.munistgo.cl/adulto-mayor/",
    tipo_link: "DEDICADA",
  },
  {
    comuna: "Vitacura",
    nombre_programa: "Centros de Día para Personas Mayores Vitacura",
    descripcion: "Tres centros de día con actividades presenciales para personas mayores de la comuna.",
    telefono: "222402522",
    correo: "secciondepersonasmayores@vitacura.cl",
    link: "https://vitacura.cl/vecinos/centro-de-dia-para-personas-mayores/",
    tipo_link: "DEDICADA",
  },
];

export function getComunaData(comuna: string): ComunaPrograma | null {
  return COMUNAS_DATA.find(
    c => c.comuna.toLowerCase() === comuna.toLowerCase()
  ) ?? null;
}
